version: "3.9"
services:
  nats:
    image: nats:2.10
    ports: ["4222:4222", "8222:8222"]
    command: ["-js", "-m", "8222"]
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  mongo_data:
